### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by sukury47** [irshuLx/Android-WYSIWYG-Editor#1]
I am trying to use android-wysiwyg-editor in fragment.
but I've got a rendering problem with below exception.

could you help me?

java.lang.ClassCastException: com.android.layoutlib.bridge.android.BridgeContext cannot be cast to android.app.Activity
    at com.github.irshulx.BaseClass.<init>(BaseClass.java:73)
    at com.github.irshulx.Editor.<init>(Editor.java:26)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

**Comment by irshuLx** [comment]
@sukury47 , i know this is way too late. My deepest apologies. Will release a patch for this over the weekend.

**Comment by freecodecamphimanshu** [comment]
i am not write numeric value please check  sir...

**Comment by SumeshBalakrishnan** [comment]
The above isssue only in lower than 6.0 android only

**Comment by freecodecamphimanshu** [comment]
but i have face this issue in android 7.0

**Comment by SumeshBalakrishnan** [comment]
I will share my code Thursday morning
