### ISSUE TITLE
laser-native-editor:2.0.0 Gradle error

### ISSUE THREAD

**Issue by elnurvl** [irshuLx/Android-WYSIWYG-Editor#17]
Downloading with gradle is impossible. I use this line in gradle module file:
`compile 'com.github.irshulx:laser-native-editor:2.0.0'`

Compiler gives failed to resolve error. I use the latest version of Android Studio.

**Comment by sesesmith30** [comment]
yeah me too...Am getting the same error

**Comment by irshuLx** [comment]
Sorry folks, the upload somehow didnt update the package. It works now.
