### ISSUE TITLE
Copy paste issue

### ISSUE THREAD

**Issue by naveendew** [irshuLx/Android-WYSIWYG-Editor#21]
pasting multiple lines when copy from clipboard.
Android 5.0.1

**Comment by Seviath** [comment]
Another work round to do this is paste programatically when button pressed (Custom button in my case).
` CharSequence textToPaste = null;
                android.content.ClipboardManager clipboard = (android.content.ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
                if (clipboard.getPrimaryClip() != null) {
                    android.content.ClipData.Item item = clipboard.getPrimaryClip().getItemAt(0);
                    textToPaste = item.getText();
                }
                content.render(textToPaste.toString());`
