### ISSUE TITLE
gradle 3.3 - Unable to add dependency

### ISSUE THREAD

**Issue by ritesh94** [irshuLx/Android-WYSIWYG-Editor#24]
compile 'com.github.irshulx:laser-native-editor:2.0.3'

Error:(50, 13) Failed to resolve: com.github.irshulx:laser-native-editor:2.0.3

**Comment by Aroniez** [comment]
same problem here

**Comment by AbhijitKurane** [comment]
Hello, 
I'm facing same issue.
Can anyone guide in case if you have resolved the issue at your end.

--
Thanks,
Abhijit

**Comment by pliratu** [comment]
same here

**Comment by AbhijitKurane** [comment]
I have added it now locally. As implemented in the sample project

**Comment by irshuLx** [comment]
sorry for leaving it unattended for so long, fixed on the commit 964d37d.
