### ISSUE TITLE
How to remove auto focus from editor

### ISSUE THREAD

**Issue by sunnyaditya** [irshuLx/Android-WYSIWYG-Editor#43]
I have 1 Edittext with named "title" before this editot and I would like to have focus on that title edittext when screen open but it show the focus on this editor.

I called below api to remove focus but failed.

`      description.clearAllContents();
        description.clearChildFocus(description);
        title.requestFocus();
        description.clearFocus();`

Is there any way to remove focus from editor in starting?

**Comment by irshuLx** [comment]
I've added support to clear focus on render, please refer to e89dfe6a6c3f3d48eb9681db6ee61f29e1be917a

```
<com.github.irshulx.Editor
                android:layout_width="match_parent"
                android:id="@+id/editor"
                android:focusable="false"
                android:focusableInTouchMode="true"
                app:auto_focus="false"
                app:render_type="Editor"
                app:placeholder="Start writing here..." />

```
