### ISSUE TITLE
Uploaded image is not uploaded .instead some game image url is added.

### ISSUE THREAD

**Issue by imneeraj** [irshuLx/Android-WYSIWYG-Editor#47]
when getting the content the uploaded image is changed to some game image URL " http://www.videogamesblogger.com/wp-content/uploads/2015/08/metal-gear-solid-5-the-phantom-pain-cheats-640x325.jpg".

where is my uploaded image?

**Comment by irshuLx** [comment]
I believe this come from copying the sample code.

[1. ](https://github.com/irshuLx/Android-WYSIWYG-Editor/blob/master/app/src/main/java/com/github/irshulx/qapp/EditorTestActivity.java)
The upload will have to be done by yourself, and insert the resulting url by `editor.onImageUploadComplete(String url);`
