### ISSUE TITLE
there is bug that image sequence when render_type="Editor"

### ISSUE THREAD

**Issue by idubakkeun** [irshuLx/Android-WYSIWYG-Editor#58]
hi your WYSIWYG is very good!! 
but there is bug.
fix it please :)

first editor and save
-image
-text
-image
-text

after open the text and images are very good(render_type Renderer)
-image
-text
-image
-text

but reload for modify(render_type Editor)
-image
-image
-text
-text

check out please!! :)

**Comment by hemantparmar23** [comment]
same as Issue #27

**Comment by idubakkeun** [comment]
> same as Issue #27

there was the same issue...thanks~!

**Comment by irshuLx** [comment]
This has been fixed on the version 2.3.2,  https://github.com/irshuLx/Android-WYSIWYG-Editor/releases/tag/2.3.2. Please give it a try.
