### ISSUE TITLE
upload pdf, zip, video and even record audio!

### ISSUE THREAD

**Issue by gonbad** [irshuLx/Android-WYSIWYG-Editor#7]
It is desirable to have some button next to upload image that after click, selects a file and uploads it to server and inserts it's link at a new line.
of a button that after click, we record an audio and upload it to server and embed it to the document with <audio> tag.
and two buttons to select and  upload audio and video as well.
all you should do putting some ImageButtons and implementing these methods:
editor.insertLink(String displayName ,String url)
editor.insertAudio(Uri file, String url, String fileName)
editor.insertVideo(Uri file, String url, String fileName)
all that elements will be displayed in new line

**Comment by irshuLx** [comment]
You can upload the file using a picker and insert the link via the api to the editor.

**Comment by gonbad** [comment]
how?
the method is private!
private void InsertLink(String uri) 
public method that use this method:
public void InsertLink() {//no argument
please implement this method in editor:
editor.insertLink(String displayName ,String url)
