### ISSUE TITLE
Update Glide Version

### ISSUE THREAD

**Issue by SanjuChauhan** [irshuLx/Android-WYSIWYG-Editor#72]
I have implement your library Android-WYSIWYG-Editor in my project and i have also implement **glide(4.9.0)** latest library version in my project which you have also implemented in your library with version **glide(4.8.0)**. 

And now **gradle is giving conflict** for different glide versions. I have to use latest version of glide because of it's new feature which I am using in my project.

Can you please update glide(4.9.0) latest version in your library.

**Comment by irshuLx** [comment]
I've updated glide to 4.9.0. Apologies for the delay.
