### ISSUE TITLE
Help: Is this library a good option for my use case ?

### ISSUE THREAD

**Issue by quanta-kt** [irshuLx/Android-WYSIWYG-Editor#79]
I'm writing an app which allows teachers to upload notes and students to view. Is this library a proper solution for letting teachers create notes content and students to view it? If no, what should I be using?

I'm just a student, and it's just a personal project.

**Comment by yunjaena** [comment]
If you need to insert image into note you need a server to upload. And if you have server to upload (html and image etc..) I think you can make it with this library.
